QT_website/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from QT_store import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('categories/', views.categories, name='categories'),
    path('category/<int:category_id>/', views.category_products, name='category_products'),
    path('search/', views.search, name='search'),
    path('about/', views.aboutus, name='aboutus'),
    path('whowe/', views.whowe, name='whowe'),
    path('partners/', views.partners_view, name='partners'),
    path('contact/', views.contactus, name='contactus'),
    path('faq/', views.faq, name='faq'),
    path('map/', views.map, name='map'),
    path('news/', views.news, name='news'),
    path('support/', views.support, name='support'),
    path('product/<int:product_id>/', views.product_detail, name='product_detail'),
    path('cart/', views.cart, name='cart'),
    path('cart/delete/<int:item_id>/', views.delete_cart_item, name='delete_cart_item'),
    path('order/create/', views.order_create, name='order_create'),
    path('order/<int:order_id>/', views.user_order_details, name='user_order_details'),
    path('get_category_products/', views.get_category_products, name='get_category_products'),
    path('lab/', views.lab, name='lab'),
    path('login/', views.login_view, name='login'),
    path('signup/', views.signup_view, name='signup'),
    path('profile/', views.profile_view, name='profile'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('commercial_offer/', views.commercial_offer, name='commercial_offer'),
    path('commercial_request/<int:commercial_request_id>/', views.commercial_request_detail_user, name='commercial_request_detail_user'),

    path('myadmin/dashboard/', views.dashboard, name='dashboard'),
    path('myadmin/feedbacks/', views.feedbacks, name='feedbacks'),
    path('myadmin/update_feedbacks_read_status/', views.update_feedbacks_read_status, name='update_feedbacks_read_status'),
    path('myadmin/orders/', views.orders, name='orders'),
    path('myadmin/update_order_status/', views.update_order_status, name='update_order_status'),
    path('myadmin/order/<int:order_id>/', views.order_details, name='order_details'),
    path('myadmin/order/<int:order_id>/approve/', views.approve_price, name='approve_price'),
    path('myadmin/products/', views.products, name='products'),
    path('myadmin/requests/', views.requests, name='requests'),
    path('myadmin/users/', views.users, name='users'),
    path('myadmin/edit/<int:pk>/', views.edit_product, name='edit_product'),
    path('myadmin/add/', views.add_product, name='add_product'),
    path('myadmin/delete/<int:pk>/', views.delete_product, name='delete_product'),
    path('myadmin/approve_request/<int:request_id>/', views.approve_request, name='approve_request'),
    path('myadmin/reject_request/<int:request_id>/', views.reject_request, name='reject_request'),

    path('myadmin/commercial_requests/', views.commercial_requests_list, name='commercial_requests_list'),
    path('myadmin/commercial_request/<int:commercial_request_id>/', views.commercial_request_detail, name='commercial_request_detail'),
    path('commercial_request/document/<int:commercial_request_id>/', views.commercial_request_document, name='commercial_request_document'),  
] 

# Добавьте обработку медиа-файлов
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Обработка статических файлов
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

QT_store/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import *
from django.forms import inlineformset_factory
from django_recaptcha.fields import ReCaptchaField

class FeedbackForm(forms.ModelForm):
    name = forms.CharField(label='Имя', max_length=100, error_messages={'required': 'Это поле обязательно для заполнения'})
    email = forms.EmailField(label='Email', error_messages={'required': 'Это поле обязательно для заполнения'})
    phone = forms.CharField(label='Телефон', max_length=15, error_messages={'required': 'Это поле обязательно для заполнения'})
    message = forms.CharField(label='Сообщение', widget=forms.Textarea, error_messages={'required': 'Это поле обязательно для заполнения'})
    captcha = ReCaptchaField(error_messages={'required': 'Это поле обязательно для заполнения'})
    class Meta:
        model = Feedback
        fields = ['name', 'phone', 'email', 'message']

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'  

class ProductImageForm(forms.ModelForm):
    class Meta:
        model = ProductImage
        fields = ['image']

class ProductDescriptionForm(forms.ModelForm):
    class Meta:
        model = ProductDescription
        fields = ['title', 'image', 'text']

class RegistrationRequestForm(forms.ModelForm):
    captcha = ReCaptchaField(error_messages={'required': 'Это поле обязательно для заполнения'})
    class Meta:
        model = RegistrationRequest
        fields = ['first_name', 'last_name', 'organization', 'email', 'phone_number']

class AddToCartForm(forms.ModelForm):
    class Meta:
        model = CartItem
        fields = [
            'product', 'note', 'quantity', 'processor', 'mother', 'ram', 
            'storage', 'graphics', 'operating_system', 'screen_sizes', 
            'screen_type', 'screen_resolution', 'touch_screen_touches', 
            'formfactor', 'webcam', 'keyset', 'keyboard_backlight', 
            'power_supplies', 'sizes', 'controllers'
        ]

    def __init__(self, *args, **kwargs):
        product = kwargs.pop('product', None)
        super(AddToCartForm, self).__init__(*args, **kwargs)
        if product:
            self.fields['product'].initial = product
            self.fields['product'].disabled = True
            self.fields['product'].widget = forms.HiddenInput()
            self.fields['processor'].queryset = product.processor.all()
            self.fields['mother'].queryset = product.mother.all()
            self.fields['ram'].queryset = product.ram.all()
            self.fields['storage'].queryset = product.storage.all()
            self.fields['graphics'].queryset = product.graphics.all()
            self.fields['operating_system'].queryset = product.operating_system.all()
            self.fields['screen_sizes'].queryset = product.screen_sizes.all()
            self.fields['screen_type'].queryset = product.screen_type.all()
            self.fields['screen_resolution'].queryset = product.screen_resolution.all()
            self.fields['touch_screen_touches'].queryset = product.touch_screen_touches.all()
            self.fields['formfactor'].queryset = product.formfactor.all()
            self.fields['webcam'].queryset = product.webcam.all()
            self.fields['keyset'].queryset = product.keyset.all()
            self.fields['keyboard_backlight'].queryset = product.keyboard_backlight.all()
            self.fields['power_supplies'].queryset = product.power_supplies.all()
            self.fields['sizes'].queryset = product.sizes.all()
            self.fields['controllers'].queryset = product.controllers.all()

class OrderCreateForm(forms.Form):
    delivery_address = forms.CharField(widget=forms.Textarea, required=True)

class ProductItemForm(forms.ModelForm):
    class Meta:
        model = ProductItem
        exclude = ('commercial_request', 'total_price', 'price')

class ProductItemPriceForm(forms.ModelForm):
    class Meta:
        model = ProductItem
        fields = ['price']

QT_store/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.admin.views.decorators import staff_member_required
from .models import *
from collections import defaultdict
from django.http import HttpResponse, JsonResponse
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import AuthenticationForm
from .forms import *
from django.contrib.auth.decorators import user_passes_test
import random
import string
from decimal import Decimal
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.core.mail import send_mail
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.core.exceptions import PermissionDenied
from django.conf import settings
import os

def is_staff(user):
    return user.is_staff

def home(request):
    return render(request, 'home.html')

def categories(request):
    return render(request, 'categories.html')

def category_products(request, category_id):
    category = Category.objects.get(pk=category_id)
    products = Product.objects.filter(category=category)
    return render(request, 'category_products.html', {'category': category, 'products': products})

def product_detail(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    descriptions = product.descriptions.all()
    similar_products = Product.objects.filter(category=product.category).exclude(id=product.id)[:5] 

    processors_by_brand = defaultdict(lambda: defaultdict(list))
    for processor in product.processor.all():
        processors_by_brand[processor.brand.name][processor.line.name].append(processor.series or '')
    processors_by_brand = {brand: dict(lines) for brand, lines in processors_by_brand.items()}

    motherboards_by_line = defaultdict(lambda: defaultdict(list))
    for motherboard in product.mother.all():
        motherboards_by_line[motherboard.line][motherboard.type].append(motherboard.name)
    motherboards_by_line = {line: dict(sorted(types.items())) for line, types in motherboards_by_line.items()}

    ram_by_type = defaultdict(list)
    for ram in product.ram.all():
        if ram.size is not None:
            ram_by_type[ram.type].append(ram.size)
    ram_by_type = {ram_type: sorted(sizes, key=lambda x: int(x)) for ram_type, sizes in ram_by_type.items()}

    all_ram_sizes = [int(size) for sizes in ram_by_type.values() for size in sizes if size is not None]
    min_ram_size = min(all_ram_sizes) if all_ram_sizes else None
    max_ram_size = max(all_ram_sizes) if all_ram_sizes else None

    storage_by_type = defaultdict(list)
    for storage in product.storage.all():
        if storage.size is not None:
            storage_by_type[storage.type].append(storage.size)
    storage_by_type = {storage_type: sorted(sizes, key=lambda x: int(x)) for storage_type, sizes in storage_by_type.items()}

    formatted_storage_by_type = {}
    for storage_type, sizes in storage_by_type.items():
        formatted_sizes = []
        for size in sizes:
            if size is not None:
                size_int = int(size)
                unit = "TB" if size_int >= 1024 else "GB"
                formatted_sizes.append((size_int / 1024 if unit == "TB" else size_int, unit))
        formatted_storage_by_type[storage_type] = formatted_sizes

    all_sizes = [int(size) for sizes in storage_by_type.values() for size in sizes if size is not None]
    min_storage_size = min(all_sizes) if all_sizes else None
    max_storage_size = max(all_sizes) if all_sizes else None
    min_storage_unit = "GB"
    max_storage_unit = "GB"
    if min_storage_size is not None and min_storage_size >= 1024:
        min_storage_size = min_storage_size / 1024
        min_storage_unit = "TB"
    if max_storage_size is not None and max_storage_size >= 1024:
        max_storage_size = max_storage_size / 1024
        max_storage_unit = "TB"

    if request.method == 'POST':
        form = AddToCartForm(request.POST, product=product)
        if form.is_valid():
            cart, created = Cart.objects.get_or_create(user=request.user)
            cart_item = form.save(commit=False)
            cart_item.cart = cart
            cart_item.save()
            return redirect('cart')
        else:
            print(form.errors)  # Выводим ошибки формы в консоль для отладки
    else:
        form = AddToCartForm(product=product)


    context = {
        'product': product,
        'similar_products': similar_products,
        'descriptions': descriptions,
        'processors_by_brand': processors_by_brand,
        'ram_by_type': ram_by_type,
        'storage_by_type': storage_by_type,
        'min_ram_size': min_ram_size,
        'max_ram_size': max_ram_size,
        'min_storage_size': min_storage_size,
        'max_storage_size': max_storage_size,
        'min_storage_unit': min_storage_unit,
        'max_storage_unit': max_storage_unit,
        'formatted_storage_by_type': formatted_storage_by_type,
        'motherboards_by_line': motherboards_by_line,
        'form': form,
    }
    return render(request, 'product_details.html', context)

def aboutus(request):
    return render(request, 'aboutus.html')

def whowe(request):
    return render(request, 'whowe.html')

def partners_view(request):
    return render(request, 'partners.html')

def contactus(request):
    if request.method == 'POST':
        # Проверка honey pot поля
        if 'honeypot' in request.POST and request.POST['honeypot']:
            return HttpResponse(status=403)  # Возвращаем ошибку доступа, если поле honeypot заполнено

        form = FeedbackForm(request.POST)
        if form.is_valid():
            form.save()
            if request.headers.get('x-requested-with') == 'XMLHttpRequest':
                return JsonResponse({'success': True})
            else:
                return redirect('contactus')
        else:
            errors = {field: error[0] for field, error in form.errors.items()}
            if request.headers.get('x-requested-with') == 'XMLHttpRequest':
                return JsonResponse({'success': False, 'errors': errors})
    else:
        form = FeedbackForm()
    return render(request, 'contactus.html', {'form': form})


def faq(request):
    return render(request, 'faq.html')

def map(request):
    return render(request, 'map.html')

def news(request):
    return render(request, 'news.html')

def support(request):
    return render(request, 'support.html')

def search(request):
    query = request.GET.get('q')
    if query:
        # Ищем продукты по названию или описанию
        result_products = Product.objects.filter(name__icontains=query) | Product.objects.filter(description__icontains=query)
    else:
        result_products = []
    
    context = {
        'query': query,
        'result_products': result_products,
    }
    return render(request, 'search_results.html', context)

def get_category_products(request):
    category_id = request.GET.get('category_id')
    try:
        category_products = Product.objects.filter(category_id=category_id)
        products_data = []
        for product in category_products:
            product_data = {
                'name': product.name,
                'features': product.features,  # Замените это на атрибуты продукта, которые вам нужны
                'url': product.get_absolute_url(),  # Предполагается, что у вас есть метод get_absolute_url в модели Product
            }
            # Если у вас есть модель ProductImage, получаем URL первого изображения продукта
            if product.images.exists():
                product_data['image_url'] = product.images.first().image.url
            else:
                product_data['image_url'] = ''  # По умолчанию, если изображения отсутствуют
            products_data.append(product_data)
        return JsonResponse({'products': products_data})
    except Exception as e:
        return JsonResponse({'error': str(e)}, status=500)
    

def lab(request):
    return render(request, 'lab.html')

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                if user.is_superuser:
                    return redirect('dashboard')  # Перенаправляем администратора на другую страницу
                else:
                    return redirect('/')
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form': form})

def signup_view(request):
    if request.method == 'POST':
        form = RegistrationRequestForm(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = RegistrationRequestForm()
    return render(request, 'signup.html', {'form': form})



@user_passes_test(is_staff, login_url='/login')
def dashboard(request):
    total_products = Product.objects.count()
    total_users = User.objects.count() - 1
    pending_requests = RegistrationRequest.objects.filter(status='pending').count()
    unread_feedbacks_count = Feedback.objects.filter(is_read=False).count()
    pending_orders_count = Order.objects.filter(status='pending_verification').count()

    context = {
        'total_products': total_products,
        'total_users': total_users,
        'pending_requests': pending_requests,
        'unread_feedbacks_count': unread_feedbacks_count,
        'pending_orders_count': pending_orders_count,
    }
    return render(request, 'admin_templates/dashboard.html', context)

@user_passes_test(is_staff, login_url='/')
def feedbacks(request):
    feedbacks = Feedback.objects.all()

QT_store/templates/categories.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Наши продукты
{% endblock %}
{% block content %}

<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">


    <div class="carousel-inner" style="">

      <div class="image-part2" id="" style="height: 100%; top: 0; left: 0; position: absolute; z-index: 5;">
        <div class="text-container2 text-wrap" style="">
            <div class="carousel-indicators d-flex justify-content-between w-100 m-0" style="position: relative; z-index: 5;">
                <div class="d-flex flex-column align-items-start">
                  <span class="button-label">Надпись 1</span>
                  <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                </div>
                <div class="d-flex flex-column align-items-center">
                  <span class="button-label">Надпись 2</span>
                  <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
                </div>
                <div class="d-flex flex-column align-items-end">
                  <span class="button-label">Надпись 3</span>
                  <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
                </div>
              </div>
              
        </div>
      </div>

      <div class="carousel-item active">
        <div class="image-part2" id="" style="height: 100%; top: 0; left: 0; position: absolute; z-index: 2;  background-color: rgba(0, 0, 0, 0.5);">
          <div class="text-container2 text-wrap" style="">
              <p class="text-start"> <strong style="color: #00a2e8;">QazTech</strong><strong> Lab</strong></p>
              <h4 class="title" style="font-size: 30px; margin-top: 20px; padding-bottom: 6px; word-break: break-word; line-height: 30px;">Современные технологии и новаторские разработки.</h4>
              <p class="text" style="font-size: 18px;">Наши технологии основаны на умных и интуитивно понятных функциях, которые призваны упростить и улучшить опыт работы пользователей.</p>
          </div>
      </div>
        <img src="{% static 'images/city.jpg' %}" class="d-block w-100" alt="..."  style="object-position: bottom; height: 500px; object-fit: cover;">
      </div>
      <div class="carousel-item">
        <div class="image-part2" id="" style="height: 100%; top: 0; left: 0; position: absolute; z-index: 2;  background-color: rgba(0, 0, 0, 0.5);">
          <div class="text-container2 text-wrap" style="">
              <p class="text-start"> <strong style="color: #00a2e8;">QazTech</strong><strong> Lab</strong></p>
              <h4 class="title" style="font-size: 30px; margin-top: 20px; padding-bottom: 6px; word-break: break-word; line-height: 30px;">Современные технологии и новаторские разработки.</h4>
              <p class="text" style="font-size: 18px;">Наши технологии основаны на умных и интуитивно понятных функциях, которые призваны упростить и улучшить опыт работы пользователей.</p>
          </div>
      </div>
        <img src="/static/images/city.jpg" class="d-block w-100" alt="..." style="object-position: center; height: 500px; object-fit: cover;">
      </div>
      <div class="carousel-item">
        <div class="image-part2" id="" style="height: 100%; top: 0; left: 0; position: absolute; z-index: 2;  background-color: rgba(0, 0, 0, 0.5);">
          <div class="text-container2 text-wrap" style="">
              <p class="text-start"> <strong style="color: #00a2e8;">QazTech</strong><strong> Lab</strong></p>
              <h4 class="title" style="font-size: 30px; margin-top: 20px; padding-bottom: 6px; word-break: break-word; line-height: 30px;">Современные технологии и новаторские разработки.</h4>
              <p class="text" style="font-size: 18px;">Наши технологии основаны на умных и интуитивно понятных функциях, которые призваны упростить и улучшить опыт работы пользователей.</p>
          </div>
      </div>
        <img src="/static/images/city.jpg" class="d-block w-100" alt="..." style="object-position: top; height: 500px; object-fit: cover;">
      </div>
    </div>
  </div>

  <div class="container" style="width: 100%; padding-top: 3rem;">
    <div class="row g-4">
      {% for category in categories %}
        <div class="col-md-3">
            <a href="{% url 'category_products' category.id %}" class="h-100">
          <div class="card h-100">
            <img src="{{ category.image.url }}" class="card-img-top"
              alt="Hollywood Sign on The Hill" />
            <div class="card-body">
              <h5 class="card-title">{{ category.name }}</h5>
              <p class="card-text">
                {{ category.description }}
              </p>
            </div>
          </div>
            </a>
        </div>
      {% endfor %}
    </div>
  </div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
{% endblock %}

QT_store/templates/category_products.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
{{ category.name }}
{% endblock %}
{% block content %}
<div class="image-container2" style="background-image: url({{ category.imageback.url }});">
    <div class="text-container3">
        {{ category.description }}
    </div>
</div>
  <div class="container" style="width: 100%; padding-top: 3rem;">
    <div class="row g-4">
        {% for product in products %}
        <div class="col-md-3">
            <a href="{% url 'product_detail' product.id %}" class="h-100">
          <div class="card h-100">
            {% if product.images.all.0.image.url %}
            <img src="{{ product.images.all.0.image.url }}" class="card-img-top"
              alt="Hollywood Sign on The Hill" style="object-fit: contain;"/>
            {% else %}
            <img src="{% static 'images/placeholder.png' %}" class="card-img-top"
            alt="Hollywood Sign on The Hill" style="object-fit: contain;"/>
            {% endif %}
            <div class="card-body d-flex">
              <div class="mt-auto">
                <h5 class="card-title" style="">{{ product.name }}</h5>
                <p class="card-text">
                  {% if product.features %}
                  {{ product.features }}
                  {% endif %}
                </p>
              </div>
            </div>
          </div>
            </a>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

QT_store/templates/contactus.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Свяжитесь с нами
{% endblock %}
{% block content %}
<div class="image-container" style="background-image: url('{% static 'images/contactus2.png' %}');">
    <div class="text-container">
        Свяжитесь с нами
    </div>
</div>

    <div class="container-inner container align-center pt-5" style="width: 80%;">
    <div class="container" style="">
        <h4 class="" style="padding-top: 8px;">Наши контакты</h4>
        <p>У нас есть несколько удобных способов связи! Вы можете написать нам на электронную почту для получения дополнительной информации или оставить отзыв. Если у вас возникли срочные вопросы или вам нужна быстрая помощь, не стесняйтесь позвонить нам по указанному на сайте номеру телефона. А также вы можете воспользоваться формой обратной связи прямо на нашем сайте. Мы всегда готовы помочь вам!</p>
        <h4 class="card-phone mbr-fonts-style display-5" style="line-height: 1; font-size: 1rem;"><strong>+7 747 700 90 49</strong></h4>
        <h4 class="card-phone mbr-fonts-style display-5" style="line-height: 1; font-size: 1rem;"><strong>+7 727 221 10 34</strong></h4>
        <h4 class="card-phone mbr-fonts-style display-5" style="line-height: 1; font-size: 1rem;"><strong>info@qt.com.kz</strong></h4>
        <h4 class="py-2">Наш адрес</h4>
        <h4 class="card-phone mbr-fonts-style display-5" style="line-height: 1; font-size: 1rem;"><strong>Проспект Райымбека, 519/3</strong></h4>
        <h4 class="card-phone mbr-fonts-style display-5" style="line-height: 1; font-size: 1rem;"><strong>Алатауский район, Алматы</strong></h4>
    </div>
            <div class="card-wrapper py-2 container" style="flex-direction: column; box-shadow: none; padding: 0;">
                <form id="feedbackForm" class="mbr-form form-with-styler" data-form-title="Form Name" action="{% url 'contactus' %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="email" data-form-email="true" value="">
                    <div class="form-row">
                        <div class="alert alert-success col-12" style="display:none;" id="successMessage">Спасибо, что заполнили форму!</div>
                        <div class="alert alert-danger col-12" style="display:none;" id="errorMessage">Ой...! какая-то проблема!</div>
                    </div>
                    <div class="dragArea form-row">
                        <div class="col-lg-12 col-md-12 col-sm-12">
                            <h4 class="mbr-fonts-style display-2 align-center pb-0" style="font-size: 1.5rem; font-weight: 500;">Оставьте отзыв</h4>
                        </div>
                        <div class="col-lg-12 col-md-12 col-sm-12"></div>
                        
                        <div data-for="name" class="col-lg-12 col-md-12 col-sm-12 form-group mb-3">
                            <input type="text" name="name" placeholder="Имя" data-form-field="name" class="form-control display-7" value="" id="name-contacts08-a">
                            <div class="text-danger" id="nameError"></div>
                        </div>
              
                        <div class="col-12 col-md-12 d-flex justify-content-center mb-3">
                            <div data-for="email" class="col-lg-6 col-md-12 col-sm-12 form-group" style="padding-left: 0; padding-right: 1rem;">
                                <input type="email" name="email" placeholder="Электронная почта" data-form-field="email" class="form-control display-7" value="" id="email-contacts08-a" autocomplete="email">
                                <div class="text-danger" id="emailError"></div>
                            </div>
                            <div data-for="phone" class="col-lg-6 col-md-12 col-sm-12 form-group" style="padding-left: 1rem; padding-right: 0;">
                                <input type="tel" name="phone" placeholder="Телефон" pattern="(\+7|8)7\d{9}" data-form-field="phone" class="form-control display-7" value="" id="phone-contacts08-a">
                                <div class="text-danger" id="phoneError"></div>
                            </div>
                        </div>
                        <div data-for="message" class="col-lg-12 col-md-12 col-sm-12 form-group mb-3">
                            <textarea name="message" placeholder="Сообщение" data-form-field="message" class="form-control display-7" id="message-contacts08-a" style="min-height: 180px;"></textarea>
                            <div class="text-danger" id="messageError"></div>
                        </div>
                        <div style="display:none;">
                            <label>Не заполняйте это поле</label>
                            <input type="text" name="honeypot" tabindex="-1" autocomplete="off">
                        </div>
                        {{ form.captcha }}
                        <div class="text-danger" id="captchaError"></div>
                        <div class="col-auto mt-3"><button type="submit" class="btn btn-lg btn-success">Отправить</button></div>
                    </div>
                </form>
            </div>
        </div>

{% endblock %}

QT_store/templates/news.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Новости
{% endblock %}
{% block content %}
{% endblock %}

QT_store/templates/order_create.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Корзина
{% endblock %}
{% block content %}
<div class="image-container2" style="background-position: center; background-image: url('{% static 'images/compare-shopping-cart-platforms-scaled.jpeg' %}');">
    <div class="text-container">
        Оформление заказа
    </div>
</div>
<div class="container d-flex flex-column" style="min-height: 42.5vh; width: 80%;">
    {% if cart_items %}
    <table class="table border mt-3 mb-2">
        <thead>
            <tr>
                <th>Продукт</th>
                <th>Количество</th>
            </tr>
        </thead>
        <tbody>
            {% for item in cart_items %}
            <tr>
                <td>{{ item.product.name }}</td>
                <td>{{ item.quantity }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>


<form method="post">
    {% csrf_token %}
    <p>
    <label for="id_delivery_address">Адрес доставки:</label>
    <textarea name="delivery_address" required="" aria-invalid="true" id="id_delivery_address" class="form-control"></textarea>
    </p>
    <button type="submit" class="btn btn-primary shadow-0 w-100 d-block mt-2">Подтвердить заказ</button>
</form>
{% else %}
<div class="alert alert-info mt-3 text-center" role="alert">
    <strong>Тут пока пусто!</strong> Добавьте товары в корзину для оформления заказа.
</div>
{% endif %}


</div>
{% endblock %}